name: Run tests and post

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: default
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          API_URL: ${{ vars.API_URL }}
          NAME: ${{ vars.NAME }}
          EMAIL: ${{ vars.EMAIL }}
          RESUME_URL: ${{ vars.RESUME_URL }}
        run: >
          docker build -t b12
          --build-arg SIGNING_KEY --build-arg NAME
          --build-arg EMAIL --build-arg RESUME_URL .

      - name: Run tests
        run: docker run --rm b12 uv run pytest

      - name: Run POST script
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          API_URL: ${{ vars.API_URL }}
          NAME: ${{ vars.NAME }}
          EMAIL: ${{ vars.EMAIL }}
          RESUME_URL: ${{ vars.RESUME_URL }}
        run: python3 .github/workflows/script.py
