name: Run tests and post

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: default
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker build -t b12 .

      - name: Run tests
        run: docker run --rm b12 uv run pytest

      - name: Run POST script
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          EMAIL: ${{ vars.EMAIL }}
          NAME: ${{ vars.NAME }}
          RESUME_URL: ${{ vars.RESUME_URL }}
        run: python3 .github/workflows/script.py
